sudo: required
services:
  - docker
language: generic
# before_install:
#   - docker build -t abdelmounaimazz/app-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true  abdelmounaimazz/app-test yarn run test
after_success:
  - docker build -t abdelmounaimazz/multi-containers-client ./client
  - docker build -t abdelmounaimazz/multi-containers-nginx ./nginx
  - docker build -t abdelmounaimazz/multi-containers-server ./server
  - docker build -t abdelmounaimazz/multi-containers-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abdelmounaimazz/multi-containers-client
  - docker push abdelmounaimazz/multi-containers-nginx
  - docker push abdelmounaimazz/multi-containers-server
  - docker push abdelmounaimazz/multi-containers-worker
# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: multi-containers
#   env: MultiContainers-env
#   bucket_name: elasticbeanstalk-us-west-2
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
